# Generated by Django 2.1.4 on 2019-02-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to=settings.AUTH_USER_MODEL)),
                ('answered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_to', to='forum.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forum.Question')),
                ('questioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questioned_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_down', models.BooleanField()),
                ('voted_on', models.DateTimeField(auto_now_add=True)),
                ('to_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_answer', to='forum.UserAnswer')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userquestion',
            unique_together={('question',)},
        ),
    ]
