# Generated by Django 2.1.4 on 2019-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='userquestion',
            old_name='question',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='votedup',
            name='voted_down',
            field=models.BooleanField(),
        ),
    ]
